### ISSUE TITLE
What does acceptProxyProtocol switch do?

### ISSUE THREAD

**Issue by amihos** [hossinasaadi/x-ui#115]

**Comment by hossinasaadi** [comment]
acceptProxyProtocol: true | false

Only used for inbound, indicating whether to receive the PROXY protocol.

PROXY protocolThe real source IP and port dedicated to passing the request, if you don't know it, please ignore this item .

Common anti-generation software (such as HAProxy, Nginx) can be configured to send it, and VLESS fallbacks xver can also send it.

When filling truein , after the bottom TCP connection is established, the requester must first send PROXY protocol v1 or v2, otherwise the connection will be closed.

https://xtls.github.io/config/transport.html#sockoptobject
